version: '3'
services:

  users-api:
    build: 
      context: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - ../../.:/usr/src/app/node_modules/boilerpress-route-sequelize
    command: ['npm', 'run', 'dev']

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
